#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
MAINEXEC="${HERE}/usr/bin/galaxy"
DRIVEREXEC="${HERE}/usr/bin/xrealAirLinuxDriver"
export LD_LIBRARY_PATH="${HERE}/usr/lib/"
# Launches the driver and display program simultaneously
exec "${DRIVEREXEC}" & "${MAINEXEC}"
